### ISSUE TITLE
前缀选择

### ISSUE THREAD

**Issue by dezng** [dmytrodanylyk/folding-plugin#2] opened 2015-07-25 04:53 UTC
开发分很多组，我们组的资源有固定的前缀，现在版本默认以一个下划线区分的前缀进行分组，然后全分到一个组了，能不能自己选择前缀进行分组

**Comment by dmytrodanylyk** [comment] 2015-07-25 14:27
@dezng Hi, can you explain in English?

**Comment by Rainer-Lang** [comment] 2015-07-25 15:33
via Google Translator (maybe this helps...)
Title:
Prefix Select

Comment:
Development divided into many groups, resources, our group has a fixed prefix, the current version of the default prefix an underscore to distinguish grouping, and then assigned to a whole group, and can not own prefixes group

**Comment by cffz0225** [comment] 2015-07-26 12:56
sometimes , i always use it ,from example： ”activity_home.xml“  rather than “home_activity.xml",so could you add the  more flexible setting. thanks ！

**Comment by Rainer-Lang** [comment] 2015-07-26 13:19
@dmytrodanylyk Maybe use a config file to let the user define the rule of grouping.

**Comment by dmytrodanylyk** [comment] 2015-07-27 16:47
Closing this ticket as it's duplicate of #1

**Closed by dmytrodanylyk** 2015-07-27 16:47 UTC
Labels: enhancement
